version: '3.1'
services:
  axondb:
    image: axondb:latest
    ports:
      - 8023:8023
      - 8123:8123
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
